config/routes.rb
Rails.application.routes.draw do

  Rails.application.routes.draw do
    mount_ember_app :frontend, to: "/"
  end

  root 'binsizes#index'
  resources :binsizes
  resources :packages#, only: [:create, :update, :destroy]

end

app/models/binsize.rb
class Binsize < ActiveRecord::Base

  default_scope {order(id: :asc)}

  has_many :packages, dependent: :destroy
end

app/models/package.rb
class Package < ActiveRecord::Base

  validates :val, :unit, :bytes, :percent, :binsize_id, presence: true

  belongs_to :binsize

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/binsizes_controller.rb
class BinsizesController < ApplicationController
  before_action :set_binsize, only: [:show, :edit, :update, :destroy]

  # GET /binsizes
  # GET /binsizes.json
  def index
    @binsizes = Binsize.all
  end

  # GET /binsizes/1
  # GET /binsizes/1.json
  def show
  end

  # GET /binsizes/new
  def new
    @binsize = Binsize.new
  end

  # GET /binsizes/1/edit
  def edit
  end

  # POST /binsizes
  # POST /binsizes.json
  def create
    @binsize = Binsize.new
    @binsize.from_json(binsize_params)

    respond_to do |format|
      if @binsize.save
        format.html { redirect_to @binsize, notice: 'Binsize was successfully created.' }
        format.json { render :show, status: :created, location: @binsize }
      else
        format.html { render :new }
        format.json { render json: @binsize.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /binsizes/1
  # PATCH/PUT /binsizes/1.json
  def update
    respond_to do |format|

      @binsize.from_json(binsize_params)

      if @binsize.save
        format.html { redirect_to @binsize, notice: 'Binsize was successfully updated.' }
        format.json { render :show, status: :ok, location: @binsize }
      else
        format.html { render :edit }
        format.json { render json: @binsize.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /binsizes/1
  # DELETE /binsizes/1.json
  def destroy
    @binsize.destroy
    respond_to do |format|
      format.html { redirect_to binsizes_url, notice: 'Binsize was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_binsize
      @binsizes = Binsize.where(id: params[:id])
      @binsize = @binsizes.first
      #@binsize = Binsize.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def binsize_params
      params[:data][:attributes].to_json
    end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :set_package, only: [:update, :destroy]

  def create
    @package = Package.new
    @package.from_json(package_params)
    @package.binsize_id = params[:data][:relationships][:binsize][:data][:id]

    if @package.save
      render :update, status: 201
    else
      render :update, status: :unprocessable_entity
    end
  end

  def update
    @package.from_json(package_params)
    if @package.save
      render :update, status: 200
    else
      render :update, status: :unprocessable_entity
    end
  end

  def destroy
    if @package.destroy
      render :update, status: 200
    else
      render :update, status: :unprocessable_entity
    end
  end

  private

  def package_params
    params[:data][:attributes].to_json
  end

  def set_package
    @packages = Package.where(id: params[:id])
    @package = @packages.first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/binsizes_helper.rb
module BinsizesHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/binsizes/_form.html.erb
<%= form_for(@binsize) do |f| %>
  <% if @binsize.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@binsize.errors.count, "error") %> prohibited this binsize from being saved:</h2>

      <ul>
      <% @binsize.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :const %><br>
    <%= f.check_box :const %>
  </div>
  <div class="field">
    <%= f.label :packages %><br>
    <%= f.text_field :packages %>
  </div>
  <div class="field">
    <%= f.label :avg %><br>
    <%= f.number_field :avg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/binsizes/edit.html.erb
<h1>Editing Binsize</h1>

<%= render 'form' %>

<%= link_to 'Show', @binsize %> |
<%= link_to 'Back', binsizes_path %>

app/views/binsizes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Binsizes</h1>

<table>
  <thead>
    <tr>
      <th>Weight</th>
      <th>Const</th>
      <th>Packages</th>
      <th>Avg</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @binsizes.each do |binsize| %>
      <tr>
        <td><%= binsize.weight %></td>
        <td><%= binsize.const %></td>
        <td><%= binsize.packages %></td>
        <td><%= binsize.avg %></td>
        <td><%= link_to 'Show', binsize %></td>
        <td><%= link_to 'Edit', edit_binsize_path(binsize) %></td>
        <td><%= link_to 'Destroy', binsize, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Binsize', new_binsize_path %>

app/views/binsizes/new.html.erb
<h1>New Binsize</h1>

<%= render 'form' %>

<%= link_to 'Back', binsizes_path %>

app/views/binsizes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weight:</strong>
  <%= @binsize.weight %>
</p>

<p>
  <strong>Const:</strong>
  <%= @binsize.const %>
</p>

<p>
  <strong>Packages:</strong>
  <%= @binsize.packages %>
</p>

<p>
  <strong>Avg:</strong>
  <%= @binsize.avg %>
</p>

<%= link_to 'Edit', edit_binsize_path(@binsize) %> |
<%= link_to 'Back', binsizes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BinSizes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>